### ISSUE TITLE
getting error while verifying otp

### ISSUE THREAD

**Issue by vis7** [Akash16s/OTP-in-django#5]
While sending post request with otp getting below error

```
Internal Server Error: /verify/time_based/8530067675/
Traceback (most recent call last):
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vishvajeet/vishvajeet/envs/dj/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vishvajeet/vishvajeet/test/OTP-in-django/verification/views.py", line 89, in post
    if OTP.verify(request.data["otp"]):  # Verifying the OTP
KeyError: 'otp'
```
if I changed below (48) line in views.py then it is working fine. I am not getting otp as dictionary rather getting single number
`        if OTP.verify(request.data, Mobile.counter):  # Verifying the OTP # request.data["otp"]`

The same is true for time based otp verification

**Comment by Akash16s** [comment]
Hello @vis7 ,
hmm weird, but the error shows the Key error is 'otp' in the dictionary

And this error is for time-based right?

**Comment by vis7** [comment]
Error in both time based and without time based.

I am getting blank dictionary that's why it is showing keyerror 'otp' not found. This is when I use postman

If I make request from browser the. Above change give me correct output. Ie. It gives me otp in variable rather than in dictionary format

**Comment by Akash16s** [comment]
Okay so this is an error in making API call

because in pyotp you need to verify it using ```OTP.verify([OTP], [Counter])```

**Comment by Akash16s** [comment]
Hope the issue is resolved?

**Comment by vis7** [comment]
No getting error. I will get back to you within 4-5 hours

**Comment by vis7** [comment]
Apologies for late reply. I am not able to reproduce this error. You can close it.

**Comment by Akash16s** [comment]
Okay thanks
